name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install Requirements
        run:
          pip install -r requirements/dev.txt
      - name: Pylint
        run:
          pylint src/
      - name: Black
        run:
          black --check ./
      - name: Type Check (mypy)
        run: mypy src --strict
