name: pull request

on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint & Check
      run: cargo fmt --check && cargo clippy --all-targets --verbose
